# Generated by Django 3.2.9 on 2022-11-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('local', 'away')},
        ),
    ]
